name: Sync templates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest upstream templates (recursive)
        env:
          GH_AUTH: |
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28'
        run: |
          set -euo pipefail

          root="templates"
          rm -rf "$root" && mkdir -p "$root"

          branch=$(curl -fsSL $GH_AUTH \
                   https://api.github.com/repos/crazy1112345/RMC14Paperwork |
                   jq -r .default_branch)

          sha=$(curl -fsSL $GH_AUTH \
                 https://api.github.com/repos/crazy1112345/RMC14Paperwork/branches/$branch |
                 jq -r .commit.sha)

          mapfile -t paths < <(
            curl -fsSL $GH_AUTH \
              "https://api.github.com/repos/crazy1112345/RMC14Paperwork/git/trees/$sha?recursive=1" |
            jq -r '.tree[] | select(.type=="blob") | .path' |
            grep -E '^Main/.*\.txt$' || true
          )

          if [[ ${#paths[@]} -eq 0 ]]; then
            echo '[]' > "$root/index.json"
            exit 0
          fi

          for path in "${paths[@]}"; do
            rel=${path#Main/}
            mkdir -p "$root/$(dirname "$rel")"
            curl -fsSL $GH_AUTH \
              -H 'Accept: application/vnd.github.v3.raw' \
              "https://raw.githubusercontent.com/crazy1112345/RMC14Paperwork/$sha/$path" \
              -o "$root/$rel"
          done

          (cd "$root" && find . -type f -name '*.txt' -print0) |
            jq -Rs -c 'split("\u0000")[:-1]' > "$root/index.json"
