name: Sync templates
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    env:                      # ← expose the PAT once, plain – no quotes, no “Bearer”
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch latest upstream templates (recursive)
        shell: bash
        run: |
          set -euo pipefail

          root="templates"
          rm -rf "$root" && mkdir -p "$root"

          gh_api() {                                   # little helper
            curl -fsSL \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H 'X-GitHub-Api-Version: 2022-11-28' \
              "$@"
          }

          branch=$(gh_api https://api.github.com/repos/crazy1112345/RMC14Paperwork |
                   jq -r .default_branch)

          sha=$(gh_api https://api.github.com/repos/crazy1112345/RMC14Paperwork/branches/$branch |
                jq -r .commit.sha)

          mapfile -t paths < <(
            gh_api "https://api.github.com/repos/crazy1112345/RMC14Paperwork/git/trees/$sha?recursive=1" |
            jq -r '.tree[] | select(.type=="blob") | .path' |
            grep -E '^Main/.*\.txt$' || true
          )

          if [[ ${#paths[@]} -eq 0 ]]; then
            echo '[]' > "$root/index.json";  exit 0
          fi

          for path in "${paths[@]}"; do
            rel=${path#Main/}
            mkdir -p "$root/$(dirname "$rel")"
            curl -fsSL \
                 -H "Authorization: Bearer $GH_TOKEN" \
                 -H 'Accept: application/vnd.github.v3.raw' \
                 "https://raw.githubusercontent.com/crazy1112345/RMC14Paperwork/$sha/$path" \
                 -o "$root/$rel"
          done

          ( cd "$root" && find . -type f -name '*.txt' -print0 ) |
            jq -Rs -c 'split("\u0000")[:-1]' > "$root/index.json"
